### ISSUE TITLE
Edit U5 Family Member does not show all the saved data field values

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#625]
- [x] `insurance_provider`, `insurance_provider_other`, `insurance_number`, `disability_type`, `rhc_card`, `nutrition_status` are form data fields that are not shown as prefilled when opening the Registration Information (shown below)
![Screenshot_20190819-101053](https://user-images.githubusercontent.com/20777928/63251305-1ffb4080-c276-11e9-8807-baca91892a55.png)

![Screenshot_20190819-101044](https://user-images.githubusercontent.com/20777928/63251299-1d98e680-c276-11e9-9215-f1a052795c66.png)

**Comment by allan-allay** [comment]
Found that when the information is null in the database it won't be displayed. But on Registration of a child U5, when the mandatory fields are filled in, the following would be missing when editing: 

> - RHC Card
> - Insurance provider
> - Insurance provider number
> - Nutrition status

The above was missing from details retrieved when getting the child details. Added the missing columns in the column list of child details retrieved so that it is fixed.

**Comment by msschroeder** [comment]
QA Jan 31 Build:
This is still not resolved. @allan-allay @manutarus Is this a really hard issue to fix? This has been an issue from the beginning and has not really been resolved.

**Comment by allan-allay** [comment]
Hi @msschroeder Following up on the initial attempts to fix this issue, it isn't a hard issue to fix. I think can be fixed with small to medium effort. 
I'll work on this since we're not tackling medium to high priority fixes

**Comment by msschroeder** [comment]
Looks good to me!
